namespace QuanLyDeTai.PKHCN.QLTK
{
    partial class QLTK
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(QLTK));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuAnimatorNS.Animation animation1 = new Bunifu.UI.WinForms.BunifuAnimatorNS.Animation();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.navpanel = new Bunifu.UI.WinForms.BunifuPanel();
            this.fillter = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TKBM = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TKGV = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TKK = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TKP = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.listTK = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.Ma = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Password = new Bunifu.UI.WinForms.BunifuTextBox();
            this.username = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.addTK = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuTransition1 = new Bunifu.UI.WinForms.BunifuTransition(this.components);
            this.edit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.delete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.cancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.navpanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.listTK)).BeginInit();
            this.SuspendLayout();
            // 
            // navpanel
            // 
            this.navpanel.BackgroundColor = System.Drawing.Color.White;
            this.navpanel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("navpanel.BackgroundImage")));
            this.navpanel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.navpanel.BorderColor = System.Drawing.Color.Transparent;
            this.navpanel.BorderRadius = 3;
            this.navpanel.BorderThickness = 1;
            this.navpanel.Controls.Add(this.fillter);
            this.navpanel.Controls.Add(this.TKBM);
            this.navpanel.Controls.Add(this.TKGV);
            this.navpanel.Controls.Add(this.TKK);
            this.navpanel.Controls.Add(this.TKP);
            this.bunifuTransition1.SetDecoration(this.navpanel, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.navpanel.Dock = System.Windows.Forms.DockStyle.Top;
            this.navpanel.Location = new System.Drawing.Point(0, 0);
            this.navpanel.Margin = new System.Windows.Forms.Padding(2);
            this.navpanel.Name = "navpanel";
            this.navpanel.ShowBorders = true;
            this.navpanel.Size = new System.Drawing.Size(1191, 88);
            this.navpanel.TabIndex = 10;
            // 
            // fillter
            // 
            this.fillter.AllowAnimations = true;
            this.fillter.AllowMouseEffects = true;
            this.fillter.AllowToggling = false;
            this.fillter.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.fillter.AnimationSpeed = 200;
            this.fillter.AutoGenerateColors = false;
            this.fillter.AutoRoundBorders = false;
            this.fillter.AutoSizeLeftIcon = true;
            this.fillter.AutoSizeRightIcon = true;
            this.fillter.BackColor = System.Drawing.Color.Transparent;
            this.fillter.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.fillter.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("fillter.BackgroundImage")));
            this.fillter.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.fillter.ButtonText = "Lọc";
            this.fillter.ButtonTextMarginLeft = 0;
            this.fillter.ColorContrastOnClick = 45;
            this.fillter.ColorContrastOnHover = 45;
            this.fillter.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.fillter.CustomizableEdges = borderEdges1;
            this.bunifuTransition1.SetDecoration(this.fillter, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.fillter.DialogResult = System.Windows.Forms.DialogResult.None;
            this.fillter.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.fillter.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.fillter.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.fillter.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.fillter.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.fillter.ForeColor = System.Drawing.Color.White;
            this.fillter.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.fillter.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.fillter.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.fillter.IconMarginLeft = 11;
            this.fillter.IconPadding = 10;
            this.fillter.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.fillter.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.fillter.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.fillter.IconSize = 25;
            this.fillter.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.fillter.IdleBorderRadius = 1;
            this.fillter.IdleBorderThickness = 1;
            this.fillter.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.fillter.IdleIconLeftImage = null;
            this.fillter.IdleIconRightImage = null;
            this.fillter.IndicateFocus = false;
            this.fillter.Location = new System.Drawing.Point(994, 18);
            this.fillter.Name = "fillter";
            this.fillter.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.fillter.OnDisabledState.BorderRadius = 1;
            this.fillter.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.fillter.OnDisabledState.BorderThickness = 1;
            this.fillter.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.fillter.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.fillter.OnDisabledState.IconLeftImage = null;
            this.fillter.OnDisabledState.IconRightImage = null;
            this.fillter.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.fillter.onHoverState.BorderRadius = 1;
            this.fillter.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.fillter.onHoverState.BorderThickness = 1;
            this.fillter.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.fillter.onHoverState.ForeColor = System.Drawing.Color.White;
            this.fillter.onHoverState.IconLeftImage = null;
            this.fillter.onHoverState.IconRightImage = null;
            this.fillter.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.fillter.OnIdleState.BorderRadius = 1;
            this.fillter.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.fillter.OnIdleState.BorderThickness = 1;
            this.fillter.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.fillter.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.fillter.OnIdleState.IconLeftImage = null;
            this.fillter.OnIdleState.IconRightImage = null;
            this.fillter.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.fillter.OnPressedState.BorderRadius = 1;
            this.fillter.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.fillter.OnPressedState.BorderThickness = 1;
            this.fillter.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.fillter.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.fillter.OnPressedState.IconLeftImage = null;
            this.fillter.OnPressedState.IconRightImage = null;
            this.fillter.Size = new System.Drawing.Size(150, 51);
            this.fillter.TabIndex = 4;
            this.fillter.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.fillter.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.fillter.TextMarginLeft = 0;
            this.fillter.TextPadding = new System.Windows.Forms.Padding(0);
            this.fillter.UseDefaultRadiusAndThickness = true;
            this.fillter.Click += new System.EventHandler(this.fillter_Click);
            // 
            // TKBM
            // 
            this.TKBM.AllowAnimations = true;
            this.TKBM.AllowMouseEffects = true;
            this.TKBM.AllowToggling = false;
            this.TKBM.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.TKBM.AnimationSpeed = 200;
            this.TKBM.AutoGenerateColors = false;
            this.TKBM.AutoRoundBorders = false;
            this.TKBM.AutoSizeLeftIcon = true;
            this.TKBM.AutoSizeRightIcon = true;
            this.TKBM.BackColor = System.Drawing.Color.Transparent;
            this.TKBM.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.TKBM.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TKBM.BackgroundImage")));
            this.TKBM.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKBM.ButtonText = "Tài khoản bộ môn";
            this.TKBM.ButtonTextMarginLeft = 0;
            this.TKBM.ColorContrastOnClick = 45;
            this.TKBM.ColorContrastOnHover = 45;
            this.TKBM.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.TKBM.CustomizableEdges = borderEdges2;
            this.bunifuTransition1.SetDecoration(this.TKBM, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.TKBM.DialogResult = System.Windows.Forms.DialogResult.None;
            this.TKBM.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.TKBM.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TKBM.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.TKBM.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.TKBM.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TKBM.ForeColor = System.Drawing.Color.White;
            this.TKBM.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.TKBM.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.TKBM.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.TKBM.IconMarginLeft = 11;
            this.TKBM.IconPadding = 10;
            this.TKBM.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.TKBM.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.TKBM.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.TKBM.IconSize = 25;
            this.TKBM.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.TKBM.IdleBorderRadius = 1;
            this.TKBM.IdleBorderThickness = 1;
            this.TKBM.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.TKBM.IdleIconLeftImage = null;
            this.TKBM.IdleIconRightImage = null;
            this.TKBM.IndicateFocus = false;
            this.TKBM.Location = new System.Drawing.Point(505, 18);
            this.TKBM.Name = "TKBM";
            this.TKBM.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.TKBM.OnDisabledState.BorderRadius = 1;
            this.TKBM.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKBM.OnDisabledState.BorderThickness = 1;
            this.TKBM.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TKBM.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.TKBM.OnDisabledState.IconLeftImage = null;
            this.TKBM.OnDisabledState.IconRightImage = null;
            this.TKBM.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TKBM.onHoverState.BorderRadius = 1;
            this.TKBM.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKBM.onHoverState.BorderThickness = 1;
            this.TKBM.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TKBM.onHoverState.ForeColor = System.Drawing.Color.White;
            this.TKBM.onHoverState.IconLeftImage = null;
            this.TKBM.onHoverState.IconRightImage = null;
            this.TKBM.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.TKBM.OnIdleState.BorderRadius = 1;
            this.TKBM.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKBM.OnIdleState.BorderThickness = 1;
            this.TKBM.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.TKBM.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.TKBM.OnIdleState.IconLeftImage = null;
            this.TKBM.OnIdleState.IconRightImage = null;
            this.TKBM.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.TKBM.OnPressedState.BorderRadius = 1;
            this.TKBM.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKBM.OnPressedState.BorderThickness = 1;
            this.TKBM.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.TKBM.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.TKBM.OnPressedState.IconLeftImage = null;
            this.TKBM.OnPressedState.IconRightImage = null;
            this.TKBM.Size = new System.Drawing.Size(150, 51);
            this.TKBM.TabIndex = 3;
            this.TKBM.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.TKBM.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.TKBM.TextMarginLeft = 0;
            this.TKBM.TextPadding = new System.Windows.Forms.Padding(0);
            this.TKBM.UseDefaultRadiusAndThickness = true;
            this.TKBM.Click += new System.EventHandler(this.TKBM_Click);
            // 
            // TKGV
            // 
            this.TKGV.AllowAnimations = true;
            this.TKGV.AllowMouseEffects = true;
            this.TKGV.AllowToggling = false;
            this.TKGV.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.TKGV.AnimationSpeed = 200;
            this.TKGV.AutoGenerateColors = false;
            this.TKGV.AutoRoundBorders = false;
            this.TKGV.AutoSizeLeftIcon = true;
            this.TKGV.AutoSizeRightIcon = true;
            this.TKGV.BackColor = System.Drawing.Color.Transparent;
            this.TKGV.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.TKGV.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TKGV.BackgroundImage")));
            this.TKGV.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKGV.ButtonText = "Tài khoản giáo viên";
            this.TKGV.ButtonTextMarginLeft = 0;
            this.TKGV.ColorContrastOnClick = 45;
            this.TKGV.ColorContrastOnHover = 45;
            this.TKGV.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.TKGV.CustomizableEdges = borderEdges3;
            this.bunifuTransition1.SetDecoration(this.TKGV, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.TKGV.DialogResult = System.Windows.Forms.DialogResult.None;
            this.TKGV.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.TKGV.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TKGV.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.TKGV.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.TKGV.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TKGV.ForeColor = System.Drawing.Color.White;
            this.TKGV.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.TKGV.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.TKGV.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.TKGV.IconMarginLeft = 11;
            this.TKGV.IconPadding = 10;
            this.TKGV.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.TKGV.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.TKGV.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.TKGV.IconSize = 25;
            this.TKGV.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.TKGV.IdleBorderRadius = 1;
            this.TKGV.IdleBorderThickness = 1;
            this.TKGV.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.TKGV.IdleIconLeftImage = null;
            this.TKGV.IdleIconRightImage = null;
            this.TKGV.IndicateFocus = false;
            this.TKGV.Location = new System.Drawing.Point(753, 18);
            this.TKGV.Name = "TKGV";
            this.TKGV.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.TKGV.OnDisabledState.BorderRadius = 1;
            this.TKGV.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKGV.OnDisabledState.BorderThickness = 1;
            this.TKGV.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TKGV.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.TKGV.OnDisabledState.IconLeftImage = null;
            this.TKGV.OnDisabledState.IconRightImage = null;
            this.TKGV.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TKGV.onHoverState.BorderRadius = 1;
            this.TKGV.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKGV.onHoverState.BorderThickness = 1;
            this.TKGV.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TKGV.onHoverState.ForeColor = System.Drawing.Color.White;
            this.TKGV.onHoverState.IconLeftImage = null;
            this.TKGV.onHoverState.IconRightImage = null;
            this.TKGV.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.TKGV.OnIdleState.BorderRadius = 1;
            this.TKGV.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKGV.OnIdleState.BorderThickness = 1;
            this.TKGV.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.TKGV.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.TKGV.OnIdleState.IconLeftImage = null;
            this.TKGV.OnIdleState.IconRightImage = null;
            this.TKGV.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.TKGV.OnPressedState.BorderRadius = 1;
            this.TKGV.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKGV.OnPressedState.BorderThickness = 1;
            this.TKGV.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.TKGV.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.TKGV.OnPressedState.IconLeftImage = null;
            this.TKGV.OnPressedState.IconRightImage = null;
            this.TKGV.Size = new System.Drawing.Size(150, 51);
            this.TKGV.TabIndex = 2;
            this.TKGV.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.TKGV.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.TKGV.TextMarginLeft = 0;
            this.TKGV.TextPadding = new System.Windows.Forms.Padding(0);
            this.TKGV.UseDefaultRadiusAndThickness = true;
            this.TKGV.Click += new System.EventHandler(this.TKGV_Click);
            // 
            // TKK
            // 
            this.TKK.AllowAnimations = true;
            this.TKK.AllowMouseEffects = true;
            this.TKK.AllowToggling = false;
            this.TKK.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.TKK.AnimationSpeed = 200;
            this.TKK.AutoGenerateColors = false;
            this.TKK.AutoRoundBorders = false;
            this.TKK.AutoSizeLeftIcon = true;
            this.TKK.AutoSizeRightIcon = true;
            this.TKK.BackColor = System.Drawing.Color.Transparent;
            this.TKK.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.TKK.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TKK.BackgroundImage")));
            this.TKK.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKK.ButtonText = "Tài khoản khoa";
            this.TKK.ButtonTextMarginLeft = 0;
            this.TKK.ColorContrastOnClick = 45;
            this.TKK.ColorContrastOnHover = 45;
            this.TKK.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.TKK.CustomizableEdges = borderEdges4;
            this.bunifuTransition1.SetDecoration(this.TKK, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.TKK.DialogResult = System.Windows.Forms.DialogResult.None;
            this.TKK.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.TKK.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TKK.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.TKK.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.TKK.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TKK.ForeColor = System.Drawing.Color.White;
            this.TKK.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.TKK.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.TKK.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.TKK.IconMarginLeft = 11;
            this.TKK.IconPadding = 10;
            this.TKK.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.TKK.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.TKK.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.TKK.IconSize = 25;
            this.TKK.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.TKK.IdleBorderRadius = 1;
            this.TKK.IdleBorderThickness = 1;
            this.TKK.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.TKK.IdleIconLeftImage = null;
            this.TKK.IdleIconRightImage = null;
            this.TKK.IndicateFocus = false;
            this.TKK.Location = new System.Drawing.Point(266, 18);
            this.TKK.Name = "TKK";
            this.TKK.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.TKK.OnDisabledState.BorderRadius = 1;
            this.TKK.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKK.OnDisabledState.BorderThickness = 1;
            this.TKK.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TKK.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.TKK.OnDisabledState.IconLeftImage = null;
            this.TKK.OnDisabledState.IconRightImage = null;
            this.TKK.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TKK.onHoverState.BorderRadius = 1;
            this.TKK.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKK.onHoverState.BorderThickness = 1;
            this.TKK.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TKK.onHoverState.ForeColor = System.Drawing.Color.White;
            this.TKK.onHoverState.IconLeftImage = null;
            this.TKK.onHoverState.IconRightImage = null;
            this.TKK.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.TKK.OnIdleState.BorderRadius = 1;
            this.TKK.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKK.OnIdleState.BorderThickness = 1;
            this.TKK.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.TKK.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.TKK.OnIdleState.IconLeftImage = null;
            this.TKK.OnIdleState.IconRightImage = null;
            this.TKK.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.TKK.OnPressedState.BorderRadius = 1;
            this.TKK.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKK.OnPressedState.BorderThickness = 1;
            this.TKK.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.TKK.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.TKK.OnPressedState.IconLeftImage = null;
            this.TKK.OnPressedState.IconRightImage = null;
            this.TKK.Size = new System.Drawing.Size(150, 51);
            this.TKK.TabIndex = 1;
            this.TKK.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.TKK.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.TKK.TextMarginLeft = 0;
            this.TKK.TextPadding = new System.Windows.Forms.Padding(0);
            this.TKK.UseDefaultRadiusAndThickness = true;
            this.TKK.Click += new System.EventHandler(this.TKK_Click);
            // 
            // TKP
            // 
            this.TKP.AllowAnimations = true;
            this.TKP.AllowMouseEffects = true;
            this.TKP.AllowToggling = false;
            this.TKP.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.TKP.AnimationSpeed = 200;
            this.TKP.AutoGenerateColors = false;
            this.TKP.AutoRoundBorders = false;
            this.TKP.AutoSizeLeftIcon = true;
            this.TKP.AutoSizeRightIcon = true;
            this.TKP.BackColor = System.Drawing.Color.Transparent;
            this.TKP.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.TKP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TKP.BackgroundImage")));
            this.TKP.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKP.ButtonText = "Tài khoản phòng";
            this.TKP.ButtonTextMarginLeft = 0;
            this.TKP.ColorContrastOnClick = 45;
            this.TKP.ColorContrastOnHover = 45;
            this.TKP.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.TKP.CustomizableEdges = borderEdges5;
            this.bunifuTransition1.SetDecoration(this.TKP, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.TKP.DialogResult = System.Windows.Forms.DialogResult.None;
            this.TKP.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.TKP.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TKP.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.TKP.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.TKP.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TKP.ForeColor = System.Drawing.Color.White;
            this.TKP.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.TKP.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.TKP.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.TKP.IconMarginLeft = 11;
            this.TKP.IconPadding = 10;
            this.TKP.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.TKP.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.TKP.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.TKP.IconSize = 25;
            this.TKP.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.TKP.IdleBorderRadius = 1;
            this.TKP.IdleBorderThickness = 1;
            this.TKP.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.TKP.IdleIconLeftImage = null;
            this.TKP.IdleIconRightImage = null;
            this.TKP.IndicateFocus = false;
            this.TKP.Location = new System.Drawing.Point(40, 18);
            this.TKP.Name = "TKP";
            this.TKP.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.TKP.OnDisabledState.BorderRadius = 1;
            this.TKP.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKP.OnDisabledState.BorderThickness = 1;
            this.TKP.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TKP.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.TKP.OnDisabledState.IconLeftImage = null;
            this.TKP.OnDisabledState.IconRightImage = null;
            this.TKP.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TKP.onHoverState.BorderRadius = 1;
            this.TKP.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKP.onHoverState.BorderThickness = 1;
            this.TKP.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TKP.onHoverState.ForeColor = System.Drawing.Color.White;
            this.TKP.onHoverState.IconLeftImage = null;
            this.TKP.onHoverState.IconRightImage = null;
            this.TKP.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.TKP.OnIdleState.BorderRadius = 1;
            this.TKP.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKP.OnIdleState.BorderThickness = 1;
            this.TKP.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.TKP.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.TKP.OnIdleState.IconLeftImage = null;
            this.TKP.OnIdleState.IconRightImage = null;
            this.TKP.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.TKP.OnPressedState.BorderRadius = 1;
            this.TKP.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TKP.OnPressedState.BorderThickness = 1;
            this.TKP.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.TKP.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.TKP.OnPressedState.IconLeftImage = null;
            this.TKP.OnPressedState.IconRightImage = null;
            this.TKP.Size = new System.Drawing.Size(150, 51);
            this.TKP.TabIndex = 0;
            this.TKP.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.TKP.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.TKP.TextMarginLeft = 0;
            this.TKP.TextPadding = new System.Windows.Forms.Padding(0);
            this.TKP.UseDefaultRadiusAndThickness = true;
            this.TKP.Click += new System.EventHandler(this.TKP_Click);
            // 
            // listTK
            // 
            this.listTK.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.listTK.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.listTK.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.listTK.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.listTK.BackgroundColor = System.Drawing.Color.White;
            this.listTK.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.listTK.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.listTK.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.listTK.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.listTK.ColumnHeadersHeight = 40;
            this.listTK.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.listTK.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.listTK.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.listTK.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.listTK.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.listTK.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.listTK.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.listTK.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.listTK.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.listTK.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.listTK.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.listTK.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.listTK.CurrentTheme.Name = null;
            this.listTK.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.listTK.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.listTK.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.listTK.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.listTK.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuTransition1.SetDecoration(this.listTK, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.listTK.DefaultCellStyle = dataGridViewCellStyle3;
            this.listTK.EnableHeadersVisualStyles = false;
            this.listTK.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.listTK.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.listTK.HeaderBgColor = System.Drawing.Color.Empty;
            this.listTK.HeaderForeColor = System.Drawing.Color.White;
            this.listTK.Location = new System.Drawing.Point(0, 89);
            this.listTK.Name = "listTK";
            this.listTK.RowHeadersVisible = false;
            this.listTK.RowTemplate.Height = 40;
            this.listTK.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.listTK.Size = new System.Drawing.Size(498, 658);
            this.listTK.TabIndex = 3;
            this.listTK.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.listTK.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.Cell_click);
            // 
            // Ma
            // 
            this.Ma.AcceptsReturn = false;
            this.Ma.AcceptsTab = false;
            this.Ma.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.Ma.AnimationSpeed = 200;
            this.Ma.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Ma.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Ma.BackColor = System.Drawing.Color.Transparent;
            this.Ma.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Ma.BackgroundImage")));
            this.Ma.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Ma.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Ma.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Ma.BorderColorIdle = System.Drawing.Color.Silver;
            this.Ma.BorderRadius = 1;
            this.Ma.BorderThickness = 1;
            this.Ma.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Ma.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTransition1.SetDecoration(this.Ma, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.Ma.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Ma.DefaultText = "";
            this.Ma.FillColor = System.Drawing.Color.White;
            this.Ma.HideSelection = true;
            this.Ma.IconLeft = null;
            this.Ma.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Ma.IconPadding = 10;
            this.Ma.IconRight = null;
            this.Ma.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Ma.Lines = new string[0];
            this.Ma.Location = new System.Drawing.Point(869, 167);
            this.Ma.MaxLength = 32767;
            this.Ma.MinimumSize = new System.Drawing.Size(1, 1);
            this.Ma.Modified = false;
            this.Ma.Multiline = false;
            this.Ma.Name = "Ma";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Ma.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Ma.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Ma.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Ma.OnIdleState = stateProperties4;
            this.Ma.Padding = new System.Windows.Forms.Padding(3);
            this.Ma.PasswordChar = '\0';
            this.Ma.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Ma.PlaceholderText = "Mã";
            this.Ma.ReadOnly = false;
            this.Ma.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Ma.SelectedText = "";
            this.Ma.SelectionLength = 0;
            this.Ma.SelectionStart = 0;
            this.Ma.ShortcutsEnabled = true;
            this.Ma.Size = new System.Drawing.Size(249, 37);
            this.Ma.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Ma.TabIndex = 4;
            this.Ma.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Ma.TextMarginBottom = 0;
            this.Ma.TextMarginLeft = 3;
            this.Ma.TextMarginTop = 0;
            this.Ma.TextPlaceholder = "Mã";
            this.Ma.UseSystemPasswordChar = false;
            this.Ma.WordWrap = true;
            // 
            // Password
            // 
            this.Password.AcceptsReturn = false;
            this.Password.AcceptsTab = false;
            this.Password.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.Password.AnimationSpeed = 200;
            this.Password.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Password.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Password.BackColor = System.Drawing.Color.Transparent;
            this.Password.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Password.BackgroundImage")));
            this.Password.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Password.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Password.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Password.BorderColorIdle = System.Drawing.Color.Silver;
            this.Password.BorderRadius = 1;
            this.Password.BorderThickness = 1;
            this.Password.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Password.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTransition1.SetDecoration(this.Password, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.Password.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Password.DefaultText = "";
            this.Password.FillColor = System.Drawing.Color.White;
            this.Password.HideSelection = true;
            this.Password.IconLeft = null;
            this.Password.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Password.IconPadding = 10;
            this.Password.IconRight = null;
            this.Password.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Password.Lines = new string[0];
            this.Password.Location = new System.Drawing.Point(869, 278);
            this.Password.MaxLength = 32767;
            this.Password.MinimumSize = new System.Drawing.Size(1, 1);
            this.Password.Modified = false;
            this.Password.Multiline = false;
            this.Password.Name = "Password";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Password.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Password.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Password.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Password.OnIdleState = stateProperties8;
            this.Password.Padding = new System.Windows.Forms.Padding(3);
            this.Password.PasswordChar = '\0';
            this.Password.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Password.PlaceholderText = "Mật khẩu";
            this.Password.ReadOnly = false;
            this.Password.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Password.SelectedText = "";
            this.Password.SelectionLength = 0;
            this.Password.SelectionStart = 0;
            this.Password.ShortcutsEnabled = true;
            this.Password.Size = new System.Drawing.Size(249, 37);
            this.Password.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Password.TabIndex = 5;
            this.Password.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Password.TextMarginBottom = 0;
            this.Password.TextMarginLeft = 3;
            this.Password.TextMarginTop = 0;
            this.Password.TextPlaceholder = "Mật khẩu";
            this.Password.UseSystemPasswordChar = false;
            this.Password.WordWrap = true;
            // 
            // username
            // 
            this.username.AcceptsReturn = false;
            this.username.AcceptsTab = false;
            this.username.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.username.AnimationSpeed = 200;
            this.username.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.username.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.username.BackColor = System.Drawing.Color.Transparent;
            this.username.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("username.BackgroundImage")));
            this.username.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.username.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.username.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.username.BorderColorIdle = System.Drawing.Color.Silver;
            this.username.BorderRadius = 1;
            this.username.BorderThickness = 1;
            this.username.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.username.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTransition1.SetDecoration(this.username, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.username.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.username.DefaultText = "";
            this.username.FillColor = System.Drawing.Color.White;
            this.username.HideSelection = true;
            this.username.IconLeft = null;
            this.username.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.username.IconPadding = 10;
            this.username.IconRight = null;
            this.username.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.username.Lines = new string[0];
            this.username.Location = new System.Drawing.Point(543, 278);
            this.username.MaxLength = 32767;
            this.username.MinimumSize = new System.Drawing.Size(1, 1);
            this.username.Modified = false;
            this.username.Multiline = false;
            this.username.Name = "username";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.username.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.username.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.username.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.username.OnIdleState = stateProperties12;
            this.username.Padding = new System.Windows.Forms.Padding(3);
            this.username.PasswordChar = '\0';
            this.username.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.username.PlaceholderText = "Tên đăng nhập";
            this.username.ReadOnly = false;
            this.username.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.username.SelectedText = "";
            this.username.SelectionLength = 0;
            this.username.SelectionStart = 0;
            this.username.ShortcutsEnabled = true;
            this.username.Size = new System.Drawing.Size(249, 37);
            this.username.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.username.TabIndex = 6;
            this.username.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.username.TextMarginBottom = 0;
            this.username.TextMarginLeft = 3;
            this.username.TextMarginTop = 0;
            this.username.TextPlaceholder = "Tên đăng nhập";
            this.username.UseSystemPasswordChar = false;
            this.username.WordWrap = true;
            // 
            // ID
            // 
            this.ID.AcceptsReturn = false;
            this.ID.AcceptsTab = false;
            this.ID.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.ID.AnimationSpeed = 200;
            this.ID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ID.BackColor = System.Drawing.Color.Transparent;
            this.ID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ID.BackgroundImage")));
            this.ID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ID.BorderColorIdle = System.Drawing.Color.Silver;
            this.ID.BorderRadius = 1;
            this.ID.BorderThickness = 1;
            this.ID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTransition1.SetDecoration(this.ID, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.ID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ID.DefaultText = "";
            this.ID.FillColor = System.Drawing.Color.White;
            this.ID.HideSelection = true;
            this.ID.IconLeft = null;
            this.ID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ID.IconPadding = 10;
            this.ID.IconRight = null;
            this.ID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ID.Lines = new string[0];
            this.ID.Location = new System.Drawing.Point(543, 167);
            this.ID.MaxLength = 32767;
            this.ID.MinimumSize = new System.Drawing.Size(1, 1);
            this.ID.Modified = false;
            this.ID.Multiline = false;
            this.ID.Name = "ID";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ID.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ID.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ID.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ID.OnIdleState = stateProperties16;
            this.ID.Padding = new System.Windows.Forms.Padding(3);
            this.ID.PasswordChar = '\0';
            this.ID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ID.PlaceholderText = "ID";
            this.ID.ReadOnly = false;
            this.ID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ID.SelectedText = "";
            this.ID.SelectionLength = 0;
            this.ID.SelectionStart = 0;
            this.ID.ShortcutsEnabled = true;
            this.ID.Size = new System.Drawing.Size(249, 37);
            this.ID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ID.TabIndex = 7;
            this.ID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ID.TextMarginBottom = 0;
            this.ID.TextMarginLeft = 3;
            this.ID.TextMarginTop = 0;
            this.ID.TextPlaceholder = "ID";
            this.ID.UseSystemPasswordChar = false;
            this.ID.WordWrap = true;
            // 
            // addTK
            // 
            this.addTK.AllowAnimations = true;
            this.addTK.AllowMouseEffects = true;
            this.addTK.AllowToggling = false;
            this.addTK.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.addTK.AnimationSpeed = 200;
            this.addTK.AutoGenerateColors = false;
            this.addTK.AutoRoundBorders = false;
            this.addTK.AutoSizeLeftIcon = true;
            this.addTK.AutoSizeRightIcon = true;
            this.addTK.BackColor = System.Drawing.Color.Transparent;
            this.addTK.BackColor1 = System.Drawing.Color.Green;
            this.addTK.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addTK.BackgroundImage")));
            this.addTK.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addTK.ButtonText = "Thêm tài khoản";
            this.addTK.ButtonTextMarginLeft = 0;
            this.addTK.ColorContrastOnClick = 45;
            this.addTK.ColorContrastOnHover = 45;
            this.addTK.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.addTK.CustomizableEdges = borderEdges6;
            this.bunifuTransition1.SetDecoration(this.addTK, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.addTK.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addTK.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addTK.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addTK.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addTK.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.addTK.Font = new System.Drawing.Font("Times New Roman", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addTK.ForeColor = System.Drawing.Color.White;
            this.addTK.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addTK.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addTK.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addTK.IconMarginLeft = 11;
            this.addTK.IconPadding = 10;
            this.addTK.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addTK.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addTK.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addTK.IconSize = 25;
            this.addTK.IdleBorderColor = System.Drawing.Color.Green;
            this.addTK.IdleBorderRadius = 1;
            this.addTK.IdleBorderThickness = 1;
            this.addTK.IdleFillColor = System.Drawing.Color.Green;
            this.addTK.IdleIconLeftImage = null;
            this.addTK.IdleIconRightImage = null;
            this.addTK.IndicateFocus = false;
            this.addTK.Location = new System.Drawing.Point(543, 396);
            this.addTK.Name = "addTK";
            this.addTK.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addTK.OnDisabledState.BorderRadius = 1;
            this.addTK.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addTK.OnDisabledState.BorderThickness = 1;
            this.addTK.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addTK.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addTK.OnDisabledState.IconLeftImage = null;
            this.addTK.OnDisabledState.IconRightImage = null;
            this.addTK.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addTK.onHoverState.BorderRadius = 1;
            this.addTK.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addTK.onHoverState.BorderThickness = 1;
            this.addTK.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addTK.onHoverState.ForeColor = System.Drawing.Color.White;
            this.addTK.onHoverState.IconLeftImage = null;
            this.addTK.onHoverState.IconRightImage = null;
            this.addTK.OnIdleState.BorderColor = System.Drawing.Color.Green;
            this.addTK.OnIdleState.BorderRadius = 1;
            this.addTK.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addTK.OnIdleState.BorderThickness = 1;
            this.addTK.OnIdleState.FillColor = System.Drawing.Color.Green;
            this.addTK.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.addTK.OnIdleState.IconLeftImage = null;
            this.addTK.OnIdleState.IconRightImage = null;
            this.addTK.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addTK.OnPressedState.BorderRadius = 1;
            this.addTK.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addTK.OnPressedState.BorderThickness = 1;
            this.addTK.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addTK.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addTK.OnPressedState.IconLeftImage = null;
            this.addTK.OnPressedState.IconRightImage = null;
            this.addTK.Size = new System.Drawing.Size(100, 39);
            this.addTK.TabIndex = 8;
            this.addTK.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.addTK.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addTK.TextMarginLeft = 0;
            this.addTK.TextPadding = new System.Windows.Forms.Padding(0);
            this.addTK.UseDefaultRadiusAndThickness = true;
            this.addTK.Click += new System.EventHandler(this.addTK_Click);
            // 
            // bunifuTransition1
            // 
            this.bunifuTransition1.AnimationType = Bunifu.UI.WinForms.BunifuAnimatorNS.AnimationType.VertSlide;
            this.bunifuTransition1.Cursor = null;
            animation1.AnimateOnlyDifferences = true;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.bunifuTransition1.DefaultAnimation = animation1;
            // 
            // edit
            // 
            this.edit.AllowAnimations = true;
            this.edit.AllowMouseEffects = true;
            this.edit.AllowToggling = false;
            this.edit.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.edit.AnimationSpeed = 200;
            this.edit.AutoGenerateColors = false;
            this.edit.AutoRoundBorders = false;
            this.edit.AutoSizeLeftIcon = true;
            this.edit.AutoSizeRightIcon = true;
            this.edit.BackColor = System.Drawing.Color.Transparent;
            this.edit.BackColor1 = System.Drawing.Color.Orange;
            this.edit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("edit.BackgroundImage")));
            this.edit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.edit.ButtonText = "Đổi mật khẩu";
            this.edit.ButtonTextMarginLeft = 0;
            this.edit.ColorContrastOnClick = 45;
            this.edit.ColorContrastOnHover = 45;
            this.edit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.edit.CustomizableEdges = borderEdges7;
            this.bunifuTransition1.SetDecoration(this.edit, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.edit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.edit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.edit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.edit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.edit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.edit.Font = new System.Drawing.Font("Times New Roman", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.edit.ForeColor = System.Drawing.Color.White;
            this.edit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.edit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.edit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.edit.IconMarginLeft = 11;
            this.edit.IconPadding = 10;
            this.edit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.edit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.edit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.edit.IconSize = 25;
            this.edit.IdleBorderColor = System.Drawing.Color.Orange;
            this.edit.IdleBorderRadius = 1;
            this.edit.IdleBorderThickness = 1;
            this.edit.IdleFillColor = System.Drawing.Color.Orange;
            this.edit.IdleIconLeftImage = null;
            this.edit.IdleIconRightImage = null;
            this.edit.IndicateFocus = false;
            this.edit.Location = new System.Drawing.Point(689, 396);
            this.edit.Name = "edit";
            this.edit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.edit.OnDisabledState.BorderRadius = 1;
            this.edit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.edit.OnDisabledState.BorderThickness = 1;
            this.edit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.edit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.edit.OnDisabledState.IconLeftImage = null;
            this.edit.OnDisabledState.IconRightImage = null;
            this.edit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.edit.onHoverState.BorderRadius = 1;
            this.edit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.edit.onHoverState.BorderThickness = 1;
            this.edit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.edit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.edit.onHoverState.IconLeftImage = null;
            this.edit.onHoverState.IconRightImage = null;
            this.edit.OnIdleState.BorderColor = System.Drawing.Color.Orange;
            this.edit.OnIdleState.BorderRadius = 1;
            this.edit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.edit.OnIdleState.BorderThickness = 1;
            this.edit.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.edit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.edit.OnIdleState.IconLeftImage = null;
            this.edit.OnIdleState.IconRightImage = null;
            this.edit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.edit.OnPressedState.BorderRadius = 1;
            this.edit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.edit.OnPressedState.BorderThickness = 1;
            this.edit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.edit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.edit.OnPressedState.IconLeftImage = null;
            this.edit.OnPressedState.IconRightImage = null;
            this.edit.Size = new System.Drawing.Size(103, 39);
            this.edit.TabIndex = 11;
            this.edit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.edit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.edit.TextMarginLeft = 0;
            this.edit.TextPadding = new System.Windows.Forms.Padding(0);
            this.edit.UseDefaultRadiusAndThickness = true;
            this.edit.Click += new System.EventHandler(this.edit_Click);
            // 
            // delete
            // 
            this.delete.AllowAnimations = true;
            this.delete.AllowMouseEffects = true;
            this.delete.AllowToggling = false;
            this.delete.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.delete.AnimationSpeed = 200;
            this.delete.AutoGenerateColors = false;
            this.delete.AutoRoundBorders = false;
            this.delete.AutoSizeLeftIcon = true;
            this.delete.AutoSizeRightIcon = true;
            this.delete.BackColor = System.Drawing.Color.Transparent;
            this.delete.BackColor1 = System.Drawing.Color.Red;
            this.delete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("delete.BackgroundImage")));
            this.delete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.delete.ButtonText = "Xóa tài khoản";
            this.delete.ButtonTextMarginLeft = 0;
            this.delete.ColorContrastOnClick = 45;
            this.delete.ColorContrastOnHover = 45;
            this.delete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.delete.CustomizableEdges = borderEdges8;
            this.bunifuTransition1.SetDecoration(this.delete, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.delete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.delete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.delete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.delete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.delete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.delete.Font = new System.Drawing.Font("Times New Roman", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.delete.ForeColor = System.Drawing.Color.White;
            this.delete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.delete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.delete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.delete.IconMarginLeft = 11;
            this.delete.IconPadding = 10;
            this.delete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.delete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.delete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.delete.IconSize = 25;
            this.delete.IdleBorderColor = System.Drawing.Color.Red;
            this.delete.IdleBorderRadius = 1;
            this.delete.IdleBorderThickness = 1;
            this.delete.IdleFillColor = System.Drawing.Color.Red;
            this.delete.IdleIconLeftImage = null;
            this.delete.IdleIconRightImage = null;
            this.delete.IndicateFocus = false;
            this.delete.Location = new System.Drawing.Point(869, 396);
            this.delete.Name = "delete";
            this.delete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.delete.OnDisabledState.BorderRadius = 1;
            this.delete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.delete.OnDisabledState.BorderThickness = 1;
            this.delete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.delete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.delete.OnDisabledState.IconLeftImage = null;
            this.delete.OnDisabledState.IconRightImage = null;
            this.delete.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.delete.onHoverState.BorderRadius = 1;
            this.delete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.delete.onHoverState.BorderThickness = 1;
            this.delete.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.delete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.delete.onHoverState.IconLeftImage = null;
            this.delete.onHoverState.IconRightImage = null;
            this.delete.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.delete.OnIdleState.BorderRadius = 1;
            this.delete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.delete.OnIdleState.BorderThickness = 1;
            this.delete.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.delete.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.delete.OnIdleState.IconLeftImage = null;
            this.delete.OnIdleState.IconRightImage = null;
            this.delete.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.delete.OnPressedState.BorderRadius = 1;
            this.delete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.delete.OnPressedState.BorderThickness = 1;
            this.delete.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.delete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.delete.OnPressedState.IconLeftImage = null;
            this.delete.OnPressedState.IconRightImage = null;
            this.delete.Size = new System.Drawing.Size(98, 39);
            this.delete.TabIndex = 12;
            this.delete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.delete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.delete.TextMarginLeft = 0;
            this.delete.TextPadding = new System.Windows.Forms.Padding(0);
            this.delete.UseDefaultRadiusAndThickness = true;
            this.delete.Click += new System.EventHandler(this.delete_Click);
            // 
            // cancel
            // 
            this.cancel.AllowAnimations = true;
            this.cancel.AllowMouseEffects = true;
            this.cancel.AllowToggling = false;
            this.cancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.cancel.AnimationSpeed = 200;
            this.cancel.AutoGenerateColors = false;
            this.cancel.AutoRoundBorders = false;
            this.cancel.AutoSizeLeftIcon = true;
            this.cancel.AutoSizeRightIcon = true;
            this.cancel.BackColor = System.Drawing.Color.Transparent;
            this.cancel.BackColor1 = System.Drawing.Color.Red;
            this.cancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cancel.BackgroundImage")));
            this.cancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cancel.ButtonText = "Hủy";
            this.cancel.ButtonTextMarginLeft = 0;
            this.cancel.ColorContrastOnClick = 45;
            this.cancel.ColorContrastOnHover = 45;
            this.cancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.cancel.CustomizableEdges = borderEdges9;
            this.bunifuTransition1.SetDecoration(this.cancel, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.cancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.cancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cancel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.cancel.Font = new System.Drawing.Font("Times New Roman", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cancel.ForeColor = System.Drawing.Color.White;
            this.cancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.cancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.cancel.IconMarginLeft = 11;
            this.cancel.IconPadding = 10;
            this.cancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.cancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.cancel.IconSize = 25;
            this.cancel.IdleBorderColor = System.Drawing.Color.Red;
            this.cancel.IdleBorderRadius = 1;
            this.cancel.IdleBorderThickness = 1;
            this.cancel.IdleFillColor = System.Drawing.Color.Red;
            this.cancel.IdleIconLeftImage = null;
            this.cancel.IdleIconRightImage = null;
            this.cancel.IndicateFocus = false;
            this.cancel.Location = new System.Drawing.Point(1014, 396);
            this.cancel.Name = "cancel";
            this.cancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cancel.OnDisabledState.BorderRadius = 1;
            this.cancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cancel.OnDisabledState.BorderThickness = 1;
            this.cancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cancel.OnDisabledState.IconLeftImage = null;
            this.cancel.OnDisabledState.IconRightImage = null;
            this.cancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cancel.onHoverState.BorderRadius = 1;
            this.cancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cancel.onHoverState.BorderThickness = 1;
            this.cancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cancel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.cancel.onHoverState.IconLeftImage = null;
            this.cancel.onHoverState.IconRightImage = null;
            this.cancel.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.cancel.OnIdleState.BorderRadius = 1;
            this.cancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cancel.OnIdleState.BorderThickness = 1;
            this.cancel.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.cancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.cancel.OnIdleState.IconLeftImage = null;
            this.cancel.OnIdleState.IconRightImage = null;
            this.cancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.cancel.OnPressedState.BorderRadius = 1;
            this.cancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cancel.OnPressedState.BorderThickness = 1;
            this.cancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.cancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.cancel.OnPressedState.IconLeftImage = null;
            this.cancel.OnPressedState.IconRightImage = null;
            this.cancel.Size = new System.Drawing.Size(104, 39);
            this.cancel.TabIndex = 13;
            this.cancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.cancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.cancel.TextMarginLeft = 0;
            this.cancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.cancel.UseDefaultRadiusAndThickness = true;
            this.cancel.Click += new System.EventHandler(this.cancel_Click);
            // 
            // QLTK
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1191, 750);
            this.Controls.Add(this.cancel);
            this.Controls.Add(this.delete);
            this.Controls.Add(this.edit);
            this.Controls.Add(this.username);
            this.Controls.Add(this.listTK);
            this.Controls.Add(this.addTK);
            this.Controls.Add(this.ID);
            this.Controls.Add(this.Ma);
            this.Controls.Add(this.Password);
            this.Controls.Add(this.navpanel);
            this.bunifuTransition1.SetDecoration(this, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.Name = "QLTK";
            this.Text = "QLTK";
            this.navpanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.listTK)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel navpanel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton TKBM;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton TKGV;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton TKK;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton TKP;
        private Bunifu.UI.WinForms.BunifuDataGridView listTK;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton addTK;
        private Bunifu.UI.WinForms.BunifuTextBox ID;
        private Bunifu.UI.WinForms.BunifuTextBox username;
        private Bunifu.UI.WinForms.BunifuTextBox Password;
        private Bunifu.UI.WinForms.BunifuTextBox Ma;
        private Bunifu.UI.WinForms.BunifuTransition bunifuTransition1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton edit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton delete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton cancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton fillter;
    }
}