namespace QuanLyDeTai.User.Infor
{
    partial class Infor
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Infor));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.colorDialog1 = new System.Windows.Forms.ColorDialog();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.hoten = new Bunifu.UI.WinForms.BunifuTextBox();
            this.MaBM = new Bunifu.UI.WinForms.BunifuTextBox();
            this.gioitinh = new Bunifu.UI.WinForms.BunifuTextBox();
            this.MaKhoa = new Bunifu.UI.WinForms.BunifuTextBox();
            this.chucvu = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Capbac = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ngaysinh = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Save = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Edit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.huy = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(67, 69);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(52, 18);
            this.label1.TabIndex = 6;
            this.label1.Text = "Họ tên";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(67, 288);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(84, 18);
            this.label2.TabIndex = 7;
            this.label2.Text = "Mã bộ môn";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(365, 140);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(62, 18);
            this.label4.TabIndex = 9;
            this.label4.Text = "Chức vụ";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(364, 69);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(63, 18);
            this.label5.TabIndex = 10;
            this.label5.Text = "Cập bậc";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(67, 207);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(73, 18);
            this.label6.TabIndex = 11;
            this.label6.Text = "Ngày sinh";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(67, 140);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(62, 18);
            this.label7.TabIndex = 12;
            this.label7.Text = "Giới tính";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(364, 207);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(66, 18);
            this.label8.TabIndex = 15;
            this.label8.Text = "Mã khoa";
            // 
            // hoten
            // 
            this.hoten.AcceptsReturn = false;
            this.hoten.AcceptsTab = false;
            this.hoten.AnimationSpeed = 200;
            this.hoten.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.hoten.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.hoten.BackColor = System.Drawing.Color.Transparent;
            this.hoten.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hoten.BackgroundImage")));
            this.hoten.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.hoten.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hoten.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hoten.BorderColorIdle = System.Drawing.Color.Silver;
            this.hoten.BorderRadius = 1;
            this.hoten.BorderThickness = 1;
            this.hoten.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.hoten.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.hoten.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.hoten.DefaultText = "";
            this.hoten.FillColor = System.Drawing.Color.White;
            this.hoten.HideSelection = true;
            this.hoten.IconLeft = null;
            this.hoten.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.hoten.IconPadding = 10;
            this.hoten.IconRight = null;
            this.hoten.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.hoten.Lines = new string[0];
            this.hoten.Location = new System.Drawing.Point(154, 55);
            this.hoten.MaxLength = 32767;
            this.hoten.MinimumSize = new System.Drawing.Size(1, 1);
            this.hoten.Modified = false;
            this.hoten.Multiline = false;
            this.hoten.Name = "hoten";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.hoten.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.hoten.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.hoten.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.hoten.OnIdleState = stateProperties4;
            this.hoten.Padding = new System.Windows.Forms.Padding(3);
            this.hoten.PasswordChar = '\0';
            this.hoten.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.hoten.PlaceholderText = "Enter text";
            this.hoten.ReadOnly = false;
            this.hoten.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.hoten.SelectedText = "";
            this.hoten.SelectionLength = 0;
            this.hoten.SelectionStart = 0;
            this.hoten.ShortcutsEnabled = true;
            this.hoten.Size = new System.Drawing.Size(162, 40);
            this.hoten.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.hoten.TabIndex = 19;
            this.hoten.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.hoten.TextMarginBottom = 0;
            this.hoten.TextMarginLeft = 3;
            this.hoten.TextMarginTop = 0;
            this.hoten.TextPlaceholder = "Enter text";
            this.hoten.UseSystemPasswordChar = false;
            this.hoten.WordWrap = true;
            // 
            // MaBM
            // 
            this.MaBM.AcceptsReturn = false;
            this.MaBM.AcceptsTab = false;
            this.MaBM.AnimationSpeed = 200;
            this.MaBM.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.MaBM.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.MaBM.BackColor = System.Drawing.Color.Transparent;
            this.MaBM.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MaBM.BackgroundImage")));
            this.MaBM.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.MaBM.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MaBM.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MaBM.BorderColorIdle = System.Drawing.Color.Silver;
            this.MaBM.BorderRadius = 1;
            this.MaBM.BorderThickness = 1;
            this.MaBM.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.MaBM.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.MaBM.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MaBM.DefaultText = "";
            this.MaBM.FillColor = System.Drawing.Color.White;
            this.MaBM.HideSelection = true;
            this.MaBM.IconLeft = null;
            this.MaBM.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.MaBM.IconPadding = 10;
            this.MaBM.IconRight = null;
            this.MaBM.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.MaBM.Lines = new string[0];
            this.MaBM.Location = new System.Drawing.Point(157, 276);
            this.MaBM.MaxLength = 32767;
            this.MaBM.MinimumSize = new System.Drawing.Size(1, 1);
            this.MaBM.Modified = false;
            this.MaBM.Multiline = false;
            this.MaBM.Name = "MaBM";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MaBM.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.MaBM.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MaBM.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MaBM.OnIdleState = stateProperties8;
            this.MaBM.Padding = new System.Windows.Forms.Padding(3);
            this.MaBM.PasswordChar = '\0';
            this.MaBM.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.MaBM.PlaceholderText = "Enter text";
            this.MaBM.ReadOnly = false;
            this.MaBM.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.MaBM.SelectedText = "";
            this.MaBM.SelectionLength = 0;
            this.MaBM.SelectionStart = 0;
            this.MaBM.ShortcutsEnabled = true;
            this.MaBM.Size = new System.Drawing.Size(162, 40);
            this.MaBM.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.MaBM.TabIndex = 20;
            this.MaBM.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.MaBM.TextMarginBottom = 0;
            this.MaBM.TextMarginLeft = 3;
            this.MaBM.TextMarginTop = 0;
            this.MaBM.TextPlaceholder = "Enter text";
            this.MaBM.UseSystemPasswordChar = false;
            this.MaBM.WordWrap = true;

            // 
            // gioitinh
            // 
            this.gioitinh.AcceptsReturn = false;
            this.gioitinh.AcceptsTab = false;
            this.gioitinh.AnimationSpeed = 200;
            this.gioitinh.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.gioitinh.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.gioitinh.BackColor = System.Drawing.Color.Transparent;
            this.gioitinh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("gioitinh.BackgroundImage")));
            this.gioitinh.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.gioitinh.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.gioitinh.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.gioitinh.BorderColorIdle = System.Drawing.Color.Silver;
            this.gioitinh.BorderRadius = 1;
            this.gioitinh.BorderThickness = 1;
            this.gioitinh.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.gioitinh.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.gioitinh.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gioitinh.DefaultText = "";
            this.gioitinh.FillColor = System.Drawing.Color.White;
            this.gioitinh.HideSelection = true;
            this.gioitinh.IconLeft = null;
            this.gioitinh.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.gioitinh.IconPadding = 10;
            this.gioitinh.IconRight = null;
            this.gioitinh.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.gioitinh.Lines = new string[0];
            this.gioitinh.Location = new System.Drawing.Point(154, 126);
            this.gioitinh.MaxLength = 32767;
            this.gioitinh.MinimumSize = new System.Drawing.Size(1, 1);
            this.gioitinh.Modified = false;
            this.gioitinh.Multiline = false;
            this.gioitinh.Name = "gioitinh";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.gioitinh.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.gioitinh.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.gioitinh.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.gioitinh.OnIdleState = stateProperties12;
            this.gioitinh.Padding = new System.Windows.Forms.Padding(3);
            this.gioitinh.PasswordChar = '\0';
            this.gioitinh.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.gioitinh.PlaceholderText = "Enter text";
            this.gioitinh.ReadOnly = false;
            this.gioitinh.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.gioitinh.SelectedText = "";
            this.gioitinh.SelectionLength = 0;
            this.gioitinh.SelectionStart = 0;
            this.gioitinh.ShortcutsEnabled = true;
            this.gioitinh.Size = new System.Drawing.Size(162, 40);
            this.gioitinh.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.gioitinh.TabIndex = 21;
            this.gioitinh.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.gioitinh.TextMarginBottom = 0;
            this.gioitinh.TextMarginLeft = 3;
            this.gioitinh.TextMarginTop = 0;
            this.gioitinh.TextPlaceholder = "Enter text";
            this.gioitinh.UseSystemPasswordChar = false;
            this.gioitinh.WordWrap = true;
            // 
            // MaKhoa
            // 
            this.MaKhoa.AcceptsReturn = false;
            this.MaKhoa.AcceptsTab = false;
            this.MaKhoa.AnimationSpeed = 200;
            this.MaKhoa.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.MaKhoa.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.MaKhoa.BackColor = System.Drawing.Color.Transparent;
            this.MaKhoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MaKhoa.BackgroundImage")));
            this.MaKhoa.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.MaKhoa.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MaKhoa.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MaKhoa.BorderColorIdle = System.Drawing.Color.Silver;
            this.MaKhoa.BorderRadius = 1;
            this.MaKhoa.BorderThickness = 1;
            this.MaKhoa.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.MaKhoa.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.MaKhoa.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MaKhoa.DefaultText = "";
            this.MaKhoa.FillColor = System.Drawing.Color.White;
            this.MaKhoa.HideSelection = true;
            this.MaKhoa.IconLeft = null;
            this.MaKhoa.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.MaKhoa.IconPadding = 10;
            this.MaKhoa.IconRight = null;
            this.MaKhoa.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.MaKhoa.Lines = new string[0];
            this.MaKhoa.Location = new System.Drawing.Point(433, 195);
            this.MaKhoa.MaxLength = 32767;
            this.MaKhoa.MinimumSize = new System.Drawing.Size(1, 1);
            this.MaKhoa.Modified = false;
            this.MaKhoa.Multiline = false;
            this.MaKhoa.Name = "MaKhoa";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MaKhoa.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.MaKhoa.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MaKhoa.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MaKhoa.OnIdleState = stateProperties16;
            this.MaKhoa.Padding = new System.Windows.Forms.Padding(3);
            this.MaKhoa.PasswordChar = '\0';
            this.MaKhoa.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.MaKhoa.PlaceholderText = "Enter text";
            this.MaKhoa.ReadOnly = false;
            this.MaKhoa.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.MaKhoa.SelectedText = "";
            this.MaKhoa.SelectionLength = 0;
            this.MaKhoa.SelectionStart = 0;
            this.MaKhoa.ShortcutsEnabled = true;
            this.MaKhoa.Size = new System.Drawing.Size(162, 40);
            this.MaKhoa.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.MaKhoa.TabIndex = 22;
            this.MaKhoa.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.MaKhoa.TextMarginBottom = 0;
            this.MaKhoa.TextMarginLeft = 3;
            this.MaKhoa.TextMarginTop = 0;
            this.MaKhoa.TextPlaceholder = "Enter text";
            this.MaKhoa.UseSystemPasswordChar = false;
            this.MaKhoa.WordWrap = true;

            // chucvu
            // 
            this.chucvu.AcceptsReturn = false;
            this.chucvu.AcceptsTab = false;
            this.chucvu.AnimationSpeed = 200;
            this.chucvu.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.chucvu.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.chucvu.BackColor = System.Drawing.Color.Transparent;
            this.chucvu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("chucvu.BackgroundImage")));
            this.chucvu.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.chucvu.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.chucvu.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chucvu.BorderColorIdle = System.Drawing.Color.Silver;
            this.chucvu.BorderRadius = 1;
            this.chucvu.BorderThickness = 1;
            this.chucvu.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.chucvu.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.chucvu.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chucvu.DefaultText = "";
            this.chucvu.FillColor = System.Drawing.Color.White;
            this.chucvu.HideSelection = true;
            this.chucvu.IconLeft = null;
            this.chucvu.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.chucvu.IconPadding = 10;
            this.chucvu.IconRight = null;
            this.chucvu.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.chucvu.Lines = new string[0];
            this.chucvu.Location = new System.Drawing.Point(433, 126);
            this.chucvu.MaxLength = 32767;
            this.chucvu.MinimumSize = new System.Drawing.Size(1, 1);
            this.chucvu.Modified = false;
            this.chucvu.Multiline = false;
            this.chucvu.Name = "chucvu";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.chucvu.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.chucvu.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.chucvu.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.chucvu.OnIdleState = stateProperties20;
            this.chucvu.Padding = new System.Windows.Forms.Padding(3);
            this.chucvu.PasswordChar = '\0';
            this.chucvu.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.chucvu.PlaceholderText = "Enter text";
            this.chucvu.ReadOnly = false;
            this.chucvu.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.chucvu.SelectedText = "";
            this.chucvu.SelectionLength = 0;
            this.chucvu.SelectionStart = 0;
            this.chucvu.ShortcutsEnabled = true;
            this.chucvu.Size = new System.Drawing.Size(162, 40);
            this.chucvu.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.chucvu.TabIndex = 23;
            this.chucvu.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.chucvu.TextMarginBottom = 0;
            this.chucvu.TextMarginLeft = 3;
            this.chucvu.TextMarginTop = 0;
            this.chucvu.TextPlaceholder = "Enter text";
            this.chucvu.UseSystemPasswordChar = false;
            this.chucvu.WordWrap = true;

            // 
            // Capbac
            // 
            this.Capbac.AcceptsReturn = false;
            this.Capbac.AcceptsTab = false;
            this.Capbac.AnimationSpeed = 200;
            this.Capbac.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Capbac.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Capbac.BackColor = System.Drawing.Color.Transparent;
            this.Capbac.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Capbac.BackgroundImage")));
            this.Capbac.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Capbac.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Capbac.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Capbac.BorderColorIdle = System.Drawing.Color.Silver;
            this.Capbac.BorderRadius = 1;
            this.Capbac.BorderThickness = 1;
            this.Capbac.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Capbac.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Capbac.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Capbac.DefaultText = "";
            this.Capbac.FillColor = System.Drawing.Color.White;
            this.Capbac.HideSelection = true;
            this.Capbac.IconLeft = null;
            this.Capbac.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Capbac.IconPadding = 10;
            this.Capbac.IconRight = null;
            this.Capbac.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Capbac.Lines = new string[0];
            this.Capbac.Location = new System.Drawing.Point(433, 55);
            this.Capbac.MaxLength = 32767;
            this.Capbac.MinimumSize = new System.Drawing.Size(1, 1);
            this.Capbac.Modified = false;
            this.Capbac.Multiline = false;
            this.Capbac.Name = "Capbac";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Capbac.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Capbac.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Capbac.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Capbac.OnIdleState = stateProperties24;
            this.Capbac.Padding = new System.Windows.Forms.Padding(3);
            this.Capbac.PasswordChar = '\0';
            this.Capbac.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Capbac.PlaceholderText = "Enter text";
            this.Capbac.ReadOnly = false;
            this.Capbac.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Capbac.SelectedText = "";
            this.Capbac.SelectionLength = 0;
            this.Capbac.SelectionStart = 0;
            this.Capbac.ShortcutsEnabled = true;
            this.Capbac.Size = new System.Drawing.Size(162, 40);
            this.Capbac.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Capbac.TabIndex = 25;
            this.Capbac.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Capbac.TextMarginBottom = 0;
            this.Capbac.TextMarginLeft = 3;
            this.Capbac.TextMarginTop = 0;
            this.Capbac.TextPlaceholder = "Enter text";
            this.Capbac.UseSystemPasswordChar = false;
            this.Capbac.WordWrap = true;

            // 
            // ngaysinh
            // 
            this.ngaysinh.AcceptsReturn = false;
            this.ngaysinh.AcceptsTab = false;
            this.ngaysinh.AnimationSpeed = 200;
            this.ngaysinh.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ngaysinh.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ngaysinh.BackColor = System.Drawing.Color.Transparent;
            this.ngaysinh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ngaysinh.BackgroundImage")));
            this.ngaysinh.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ngaysinh.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ngaysinh.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ngaysinh.BorderColorIdle = System.Drawing.Color.Silver;
            this.ngaysinh.BorderRadius = 1;
            this.ngaysinh.BorderThickness = 1;
            this.ngaysinh.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ngaysinh.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ngaysinh.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ngaysinh.DefaultText = "";
            this.ngaysinh.FillColor = System.Drawing.Color.White;
            this.ngaysinh.HideSelection = true;
            this.ngaysinh.IconLeft = null;
            this.ngaysinh.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ngaysinh.IconPadding = 10;
            this.ngaysinh.IconRight = null;
            this.ngaysinh.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ngaysinh.Lines = new string[0];
            this.ngaysinh.Location = new System.Drawing.Point(154, 195);
            this.ngaysinh.MaxLength = 32767;
            this.ngaysinh.MinimumSize = new System.Drawing.Size(1, 1);
            this.ngaysinh.Modified = false;
            this.ngaysinh.Multiline = false;
            this.ngaysinh.Name = "ngaysinh";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ngaysinh.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ngaysinh.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ngaysinh.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ngaysinh.OnIdleState = stateProperties28;
            this.ngaysinh.Padding = new System.Windows.Forms.Padding(3);
            this.ngaysinh.PasswordChar = '\0';
            this.ngaysinh.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ngaysinh.PlaceholderText = "Enter text";
            this.ngaysinh.ReadOnly = false;
            this.ngaysinh.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ngaysinh.SelectedText = "";
            this.ngaysinh.SelectionLength = 0;
            this.ngaysinh.SelectionStart = 0;
            this.ngaysinh.ShortcutsEnabled = true;
            this.ngaysinh.Size = new System.Drawing.Size(162, 40);
            this.ngaysinh.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ngaysinh.TabIndex = 26;
            this.ngaysinh.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ngaysinh.TextMarginBottom = 0;
            this.ngaysinh.TextMarginLeft = 3;
            this.ngaysinh.TextMarginTop = 0;
            this.ngaysinh.TextPlaceholder = "Enter text";
            this.ngaysinh.UseSystemPasswordChar = false;
            this.ngaysinh.WordWrap = true;

            // 
            // Save
            // 
            this.Save.AllowAnimations = true;
            this.Save.AllowMouseEffects = true;
            this.Save.AllowToggling = false;
            this.Save.AnimationSpeed = 200;
            this.Save.AutoGenerateColors = false;
            this.Save.AutoRoundBorders = false;
            this.Save.AutoSizeLeftIcon = true;
            this.Save.AutoSizeRightIcon = true;
            this.Save.BackColor = System.Drawing.Color.Transparent;
            this.Save.BackColor1 = System.Drawing.Color.Lime;
            this.Save.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Save.BackgroundImage")));
            this.Save.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.ButtonText = "Lưu";
            this.Save.ButtonTextMarginLeft = 0;
            this.Save.ColorContrastOnClick = 45;
            this.Save.ColorContrastOnHover = 45;
            this.Save.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.Save.CustomizableEdges = borderEdges1;
            this.Save.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Save.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Save.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Save.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Save.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Save.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Save.ForeColor = System.Drawing.Color.White;
            this.Save.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Save.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Save.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Save.IconMarginLeft = 11;
            this.Save.IconPadding = 10;
            this.Save.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Save.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Save.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Save.IconSize = 25;
            this.Save.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.Save.IdleBorderRadius = 1;
            this.Save.IdleBorderThickness = 1;
            this.Save.IdleFillColor = System.Drawing.Color.Lime;
            this.Save.IdleIconLeftImage = null;
            this.Save.IdleIconRightImage = null;
            this.Save.IndicateFocus = false;
            this.Save.Location = new System.Drawing.Point(300, 352);
            this.Save.Name = "Save";
            this.Save.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Save.OnDisabledState.BorderRadius = 1;
            this.Save.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.OnDisabledState.BorderThickness = 1;
            this.Save.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Save.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Save.OnDisabledState.IconLeftImage = null;
            this.Save.OnDisabledState.IconRightImage = null;
            this.Save.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Save.onHoverState.BorderRadius = 1;
            this.Save.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.onHoverState.BorderThickness = 1;
            this.Save.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Save.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Save.onHoverState.IconLeftImage = null;
            this.Save.onHoverState.IconRightImage = null;
            this.Save.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.Save.OnIdleState.BorderRadius = 1;
            this.Save.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.OnIdleState.BorderThickness = 1;
            this.Save.OnIdleState.FillColor = System.Drawing.Color.Lime;
            this.Save.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Save.OnIdleState.IconLeftImage = null;
            this.Save.OnIdleState.IconRightImage = null;
            this.Save.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Save.OnPressedState.BorderRadius = 1;
            this.Save.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save.OnPressedState.BorderThickness = 1;
            this.Save.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Save.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Save.OnPressedState.IconLeftImage = null;
            this.Save.OnPressedState.IconRightImage = null;
            this.Save.Size = new System.Drawing.Size(92, 39);
            this.Save.TabIndex = 27;
            this.Save.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Save.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Save.TextMarginLeft = 0;
            this.Save.TextPadding = new System.Windows.Forms.Padding(0);
            this.Save.UseDefaultRadiusAndThickness = true;
            this.Save.Click += new System.EventHandler(this.Save_Click_1);
            // 
            // Edit
            // 
            this.Edit.AllowAnimations = true;
            this.Edit.AllowMouseEffects = true;
            this.Edit.AllowToggling = false;
            this.Edit.AnimationSpeed = 200;
            this.Edit.AutoGenerateColors = false;
            this.Edit.AutoRoundBorders = false;
            this.Edit.AutoSizeLeftIcon = true;
            this.Edit.AutoSizeRightIcon = true;
            this.Edit.BackColor = System.Drawing.Color.Transparent;
            this.Edit.BackColor1 = System.Drawing.Color.Orange;
            this.Edit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Edit.BackgroundImage")));
            this.Edit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.ButtonText = "Sửa";
            this.Edit.ButtonTextMarginLeft = 0;
            this.Edit.ColorContrastOnClick = 45;
            this.Edit.ColorContrastOnHover = 45;
            this.Edit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Edit.CustomizableEdges = borderEdges2;
            this.Edit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Edit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Edit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Edit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Edit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Edit.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Edit.ForeColor = System.Drawing.Color.White;
            this.Edit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Edit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Edit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Edit.IconMarginLeft = 11;
            this.Edit.IconPadding = 10;
            this.Edit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Edit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Edit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Edit.IconSize = 25;
            this.Edit.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.Edit.IdleBorderRadius = 1;
            this.Edit.IdleBorderThickness = 1;
            this.Edit.IdleFillColor = System.Drawing.Color.Orange;
            this.Edit.IdleIconLeftImage = null;
            this.Edit.IdleIconRightImage = null;
            this.Edit.IndicateFocus = false;
            this.Edit.Location = new System.Drawing.Point(154, 352);
            this.Edit.Name = "Edit";
            this.Edit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Edit.OnDisabledState.BorderRadius = 1;
            this.Edit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.OnDisabledState.BorderThickness = 1;
            this.Edit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Edit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Edit.OnDisabledState.IconLeftImage = null;
            this.Edit.OnDisabledState.IconRightImage = null;
            this.Edit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Edit.onHoverState.BorderRadius = 1;
            this.Edit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.onHoverState.BorderThickness = 1;
            this.Edit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Edit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Edit.onHoverState.IconLeftImage = null;
            this.Edit.onHoverState.IconRightImage = null;
            this.Edit.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.Edit.OnIdleState.BorderRadius = 1;
            this.Edit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.OnIdleState.BorderThickness = 1;
            this.Edit.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.Edit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Edit.OnIdleState.IconLeftImage = null;
            this.Edit.OnIdleState.IconRightImage = null;
            this.Edit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Edit.OnPressedState.BorderRadius = 1;
            this.Edit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit.OnPressedState.BorderThickness = 1;
            this.Edit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Edit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Edit.OnPressedState.IconLeftImage = null;
            this.Edit.OnPressedState.IconRightImage = null;
            this.Edit.Size = new System.Drawing.Size(93, 39);
            this.Edit.TabIndex = 28;
            this.Edit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Edit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Edit.TextMarginLeft = 0;
            this.Edit.TextPadding = new System.Windows.Forms.Padding(0);
            this.Edit.UseDefaultRadiusAndThickness = true;
            this.Edit.Click += new System.EventHandler(this.Edit_Click_1);
            // 
            // huy
            // 
            this.huy.AllowAnimations = true;
            this.huy.AllowMouseEffects = true;
            this.huy.AllowToggling = false;
            this.huy.AnimationSpeed = 200;
            this.huy.AutoGenerateColors = false;
            this.huy.AutoRoundBorders = false;
            this.huy.AutoSizeLeftIcon = true;
            this.huy.AutoSizeRightIcon = true;
            this.huy.BackColor = System.Drawing.Color.Transparent;
            this.huy.BackColor1 = System.Drawing.Color.Red;
            this.huy.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("huy.BackgroundImage")));
            this.huy.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.ButtonText = "Hủy";
            this.huy.ButtonTextMarginLeft = 0;
            this.huy.ColorContrastOnClick = 45;
            this.huy.ColorContrastOnHover = 45;
            this.huy.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.huy.CustomizableEdges = borderEdges3;
            this.huy.DialogResult = System.Windows.Forms.DialogResult.None;
            this.huy.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.huy.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.huy.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.huy.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.huy.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.huy.ForeColor = System.Drawing.Color.White;
            this.huy.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.huy.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.huy.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.huy.IconMarginLeft = 11;
            this.huy.IconPadding = 10;
            this.huy.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.huy.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.huy.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.huy.IconSize = 25;
            this.huy.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.huy.IdleBorderRadius = 1;
            this.huy.IdleBorderThickness = 1;
            this.huy.IdleFillColor = System.Drawing.Color.Red;
            this.huy.IdleIconLeftImage = null;
            this.huy.IdleIconRightImage = null;
            this.huy.IndicateFocus = false;
            this.huy.Location = new System.Drawing.Point(433, 352);
            this.huy.Name = "huy";
            this.huy.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.huy.OnDisabledState.BorderRadius = 1;
            this.huy.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.OnDisabledState.BorderThickness = 1;
            this.huy.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.huy.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.huy.OnDisabledState.IconLeftImage = null;
            this.huy.OnDisabledState.IconRightImage = null;
            this.huy.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.huy.onHoverState.BorderRadius = 1;
            this.huy.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.onHoverState.BorderThickness = 1;
            this.huy.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.huy.onHoverState.ForeColor = System.Drawing.Color.White;
            this.huy.onHoverState.IconLeftImage = null;
            this.huy.onHoverState.IconRightImage = null;
            this.huy.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.huy.OnIdleState.BorderRadius = 1;
            this.huy.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.OnIdleState.BorderThickness = 1;
            this.huy.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.huy.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.huy.OnIdleState.IconLeftImage = null;
            this.huy.OnIdleState.IconRightImage = null;
            this.huy.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.huy.OnPressedState.BorderRadius = 1;
            this.huy.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.huy.OnPressedState.BorderThickness = 1;
            this.huy.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.huy.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.huy.OnPressedState.IconLeftImage = null;
            this.huy.OnPressedState.IconRightImage = null;
            this.huy.Size = new System.Drawing.Size(84, 39);
            this.huy.TabIndex = 29;
            this.huy.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.huy.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.huy.TextMarginLeft = 0;
            this.huy.TextPadding = new System.Windows.Forms.Padding(0);
            this.huy.UseDefaultRadiusAndThickness = true;
            this.huy.Click += new System.EventHandler(this.huy_Click_1);
            // 
            // Infor
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.huy);
            this.Controls.Add(this.Edit);
            this.Controls.Add(this.Save);
            this.Controls.Add(this.ngaysinh);
            this.Controls.Add(this.Capbac);
            this.Controls.Add(this.chucvu);
            this.Controls.Add(this.MaKhoa);
            this.Controls.Add(this.gioitinh);
            this.Controls.Add(this.MaBM);
            this.Controls.Add(this.hoten);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Name = "Infor";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Infor_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.ColorDialog colorDialog1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuTextBox hoten;
        private Bunifu.UI.WinForms.BunifuTextBox MaBM;
        private Bunifu.UI.WinForms.BunifuTextBox gioitinh;
        private Bunifu.UI.WinForms.BunifuTextBox MaKhoa;
        private Bunifu.UI.WinForms.BunifuTextBox chucvu;
        private Bunifu.UI.WinForms.BunifuTextBox Capbac;
        private Bunifu.UI.WinForms.BunifuTextBox ngaysinh;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Save;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Edit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton huy;
    }
}